### PR TITLE
fix: Skipping credential lookup in emulator mode

### LINKED ISSUE #458: Authentication emulator fails on clean environment to required default credentials
### [REQUIRED] Step 2: Describe your environment

  * Operating System version: WSL Unix
  * Firebase SDK version: 4.6.0
  * Library version: v4.6.0
  * Firebase Product: auth emulator

### [REQUIRED] Step 3: Describe the problem

Running auth emulator with the wanted env variable FIREBASE_AUTH_EMULATOR_HOST fails.

#### Steps to reproduce:

Start a project in a clean machine. Add env variable FIREBASE_AUTH_EMULATOR_HOST and make firebase auth app.
It gives error `google: could not find default credentials. See https://developers.google.com/accounts/docs/application-default-credentials for more information.`

#### Relevant Code:

```go
conf := &firebase.Config{ProjectID: "demo-project"}
app, err := firebase.NewApp(ctx, conf)
auth, err := app.Auth(ctx)
if err != nil {
   log.Fatalf("making firebase auth failed: %v", err) // this line is hit
}
```

The problem was missing the option `firebase.NewApp(ctx, conf, option.WithoutAuthentication())`. This isn't documented anywhere. Took me an hour of searching google and trying all kinds of things.

I came across this as Github Action failed to it. Tested on a brand new EC2 ubuntu instance in Amazon and fails too. With `WithoutAuthentication()` option both work as expected.

### PR DESCRIPTION
**Pull request by hiranya911**
We currently perform a credential lookup in the emulator mode, which can result in errors if the developer hasn't specified any credentials during initialization. This PR attempts to solve this problem by defaulting to "owner" emulator credentials in the emulator mode. 

One downside of this solution is that it will cause all client options to get ignored in emulator mode. Ideally we should check if the developer has specified any credentials, and only replace that. But currently there's no clean way to implement such a replacement.

Also found a couple of existing unit tests that were taking 7 seconds each due to automatic retries. I've disabled retries for those tests thus saving 14 seconds from our unit test runs. 

Resolves #458

### CODE REVIEW

File: auth/auth.go [hunk 1]
```diff
@@ -114,7 +120,15 @@ func NewClient(ctx context.Context, conf *internal.AuthConfig) (*Client, error)
 		return nil, err
 	}
 
-	transport, _, err := transport.NewHTTPClient(ctx, conf.Opts...)
+	var opts []option.ClientOption
```
Comment (lahirumaramba) [inline auth/auth.go:123]: You must have tried this already... but just for my curiosity, can we access `conf.Opts` here without creating a new `[]option.ClientOption` and append the `ts`?

**Review by lahirumaramba — APPROVED** [review]
LGTM! Left one comment?

File: auth/auth.go (hunk 1 above)
Comment (hiranya911) [reply auth/auth.go:123]: `conf` gets passed into this function as an argument. I'm not a huge fan of modifying function arguments, since the caller usually has a reference to the same struct.

**Review by yuchenshi — APPROVED** [review]
